Adding QPE Benchmark
Qiskit/red-queen pull request #30
Opened 2022-08-02 19:12 UTC by Yelissal

2022-08-02 19:22 UTC, Lementknight approved these changes
Looks good to me. Way to go, Yelissa!

2022-08-02 19:25 UTC, Lementknight requested changes
Remove the extra qasm folder you have in the `red_queen` directory.

2022-08-09 13:24 UTC, danielleodigie reviewed
Looks good! One tiny thing with the licenses

2022-08-09 13:24 UTC, danielleodigie commented on red_queen/games/applications/run_qpe.py
> +# Part of Red Queen Project.  This file is distributed under the Apache License.
```suggestion
# Part of Red Queen Project.  This file is distributed under the Apache 2.0 License.
```

2022-08-09 13:29 UTC, keilydluna approved these changes
Fidelities look good! Don't forget its Apache 2.0 License.

2022-08-09 13:53 UTC, danielleodigie approved these changes
LGTM!

2022-08-09 13:55 UTC, Lementknight approved these changes
Looks good to me. Great job, Yelissa!

2022-08-10 12:23 UTC, mtreinish approved these changes
This LGTM, thanks for sticking with it and making all the updates. I'm ready to merge but I'd like to wait until we get #29 merged so we can get a test run for this in CI before we merge.

2022-08-10 18:17 UTC, merged